/**
 * E13 Employer-Matching — the static employer-match database.
 *
 * A deterministic, Double-the-Donation-style seed of ~30 well-known firms with a
 * match ratio (×100), an annual cap per donor, a minimum donation and an
 * integration level. The MockEmployerMatchProvider serves this list in tests and
 * by default; the seed writes the same rows to the DB. Diaspora donors typically
 * sit in tech / finance / pharma — those are well represented here. Employer
 * names carry real accents (Nestlé, Société Générale) so the multi-language
 * rendering is exercised.
 */

import { MatchProgram } from './employer-match-lookup';

const eur = (n: number): number => n * 100;

export const EMPLOYER_PROGRAMS: readonly MatchProgram[] = [
  // ---- Tech ----
  {
    domain: 'sap.com',
    employerName: 'SAP',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(10),
    integrationLevel: 'PORTAL',
    applyUrlTemplate:
      'https://match.sap.example/apply?amount={amount}&employer={employer}',
    active: true,
  },
  {
    domain: 'google.com',
    employerName: 'Google',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(5),
    integrationLevel: 'AUTO_SUBMIT',
    applyUrlTemplate:
      'https://givingathome.google.example/match?amount={amount}',
    active: true,
  },
  {
    domain: 'microsoft.com',
    employerName: 'Microsoft',
    matchRatio: 100,
    annualCapCents: eur(15000),
    minDonationCents: eur(5),
    integrationLevel: 'AUTO_SUBMIT',
    applyUrlTemplate: 'https://give.microsoft.example/match?amount={amount}',
    active: true,
  },
  {
    domain: 'apple.com',
    employerName: 'Apple',
    matchRatio: 100,
    annualCapCents: eur(10000),
    minDonationCents: eur(10),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://benevity.apple.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'amazon.com',
    employerName: 'Amazon',
    matchRatio: 50,
    annualCapCents: eur(4000),
    minDonationCents: eur(10),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://smile.amazon.example/match?amount={amount}',
    active: true,
  },
  {
    domain: 'meta.com',
    employerName: 'Meta',
    matchRatio: 100,
    annualCapCents: eur(8000),
    minDonationCents: eur(5),
    integrationLevel: 'AUTO_SUBMIT',
    applyUrlTemplate: 'https://give.meta.example/match?amount={amount}',
    active: true,
  },
  {
    domain: 'salesforce.com',
    employerName: 'Salesforce',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(10),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://give.salesforce.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'siemens.com',
    employerName: 'Siemens',
    matchRatio: 200,
    annualCapCents: eur(3000),
    minDonationCents: eur(20),
    integrationLevel: 'MANUAL',
    applyUrlTemplate: null,
    active: true,
  },
  {
    domain: 'ibm.com',
    employerName: 'IBM',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(25),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.ibm.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'intel.com',
    employerName: 'Intel',
    matchRatio: 100,
    annualCapCents: eur(10000),
    minDonationCents: eur(25),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.intel.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'oracle.com',
    employerName: 'Oracle',
    matchRatio: 100,
    annualCapCents: eur(3000),
    minDonationCents: eur(25),
    integrationLevel: 'MANUAL',
    applyUrlTemplate: null,
    active: true,
  },
  {
    domain: 'adobe.com',
    employerName: 'Adobe',
    matchRatio: 100,
    annualCapCents: eur(10000),
    minDonationCents: eur(10),
    integrationLevel: 'AUTO_SUBMIT',
    applyUrlTemplate: 'https://give.adobe.example/match?amount={amount}',
    active: true,
  },
  {
    domain: 'nvidia.com',
    employerName: 'NVIDIA',
    matchRatio: 200,
    annualCapCents: eur(10000),
    minDonationCents: eur(25),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.nvidia.example/apply?amount={amount}',
    active: true,
  },

  // ---- Finance ----
  {
    domain: 'goldmansachs.com',
    employerName: 'Goldman Sachs',
    matchRatio: 100,
    annualCapCents: eur(20000),
    minDonationCents: eur(25),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.gs.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'jpmorgan.com',
    employerName: 'JPMorgan Chase',
    matchRatio: 100,
    annualCapCents: eur(10000),
    minDonationCents: eur(25),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.jpmc.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'db.com',
    employerName: 'Deutsche Bank',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(20),
    integrationLevel: 'MANUAL',
    applyUrlTemplate: null,
    active: true,
  },
  {
    domain: 'allianz.com',
    employerName: 'Allianz',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.allianz.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'socgen.com',
    employerName: 'Société Générale',
    matchRatio: 100,
    annualCapCents: eur(4000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.socgen.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'blackrock.com',
    employerName: 'BlackRock',
    matchRatio: 200,
    annualCapCents: eur(15000),
    minDonationCents: eur(25),
    integrationLevel: 'AUTO_SUBMIT',
    applyUrlTemplate: 'https://give.blackrock.example/match?amount={amount}',
    active: true,
  },
  {
    domain: 'mastercard.com',
    employerName: 'Mastercard',
    matchRatio: 100,
    annualCapCents: eur(10000),
    minDonationCents: eur(10),
    integrationLevel: 'AUTO_SUBMIT',
    applyUrlTemplate: 'https://give.mastercard.example/match?amount={amount}',
    active: true,
  },
  {
    domain: 'visa.com',
    employerName: 'Visa',
    matchRatio: 100,
    annualCapCents: eur(10000),
    minDonationCents: eur(10),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.visa.example/apply?amount={amount}',
    active: true,
  },

  // ---- Pharma / Health ----
  {
    domain: 'novartis.com',
    employerName: 'Novartis',
    matchRatio: 100,
    annualCapCents: eur(10000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.novartis.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'roche.com',
    employerName: 'Roche',
    matchRatio: 100,
    annualCapCents: eur(8000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.roche.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'pfizer.com',
    employerName: 'Pfizer',
    matchRatio: 100,
    annualCapCents: eur(7500),
    minDonationCents: eur(25),
    integrationLevel: 'MANUAL',
    applyUrlTemplate: null,
    active: true,
  },
  {
    domain: 'bayer.com',
    employerName: 'Bayer',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.bayer.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'merck.com',
    employerName: 'Merck',
    matchRatio: 200,
    annualCapCents: eur(6000),
    minDonationCents: eur(25),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.merck.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'gsk.com',
    employerName: 'GSK',
    matchRatio: 100,
    annualCapCents: eur(5000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.gsk.example/apply?amount={amount}',
    active: true,
  },

  // ---- Consumer / other ----
  {
    domain: 'nestle.com',
    employerName: 'Nestlé',
    matchRatio: 100,
    annualCapCents: eur(4000),
    minDonationCents: eur(20),
    integrationLevel: 'MANUAL',
    applyUrlTemplate: null,
    active: true,
  },
  {
    domain: 'unilever.com',
    employerName: 'Unilever',
    matchRatio: 100,
    annualCapCents: eur(4000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.unilever.example/apply?amount={amount}',
    active: true,
  },
  {
    domain: 'shell.com',
    employerName: 'Shell',
    matchRatio: 100,
    annualCapCents: eur(6000),
    minDonationCents: eur(20),
    integrationLevel: 'PORTAL',
    applyUrlTemplate: 'https://match.shell.example/apply?amount={amount}',
    active: true,
  },
  // A deliberately inactive program — exercises the INACTIVE eligibility branch.
  {
    domain: 'legacycorp.com',
    employerName: 'Legacy Corp',
    matchRatio: 100,
    annualCapCents: eur(1000),
    minDonationCents: eur(10),
    integrationLevel: 'MANUAL',
    applyUrlTemplate: null,
    active: false,
  },
];

/** Lookup helper shared by the mock provider (and usable in tests). */
export function findProgramByDomain(domain: string): MatchProgram | null {
  const needle = domain.trim().toLowerCase();
  return EMPLOYER_PROGRAMS.find((p) => p.domain === needle) ?? null;
}
